manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: jlw
      url-base: https://github.com/josh-l-wang
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-leader-key
      remote: urob
      revision: v0.3.0
    - name: zmk-config-jlw
      remote: jlw
      revision: main # this should get pinned to 0.3
    - name: le-chiffre-stm32-zmk-config
      remote: petejohanson
      revision: main
  self:
    path: config
